language: node_js
node_js: '8'
before_script: npm install -g wcfutils
script: wcfutils
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.pages.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com/
  - secure: eYWUHxj32IRENYDGah2Ec6hzVYPtB/Oqxh/T1H/JTy20YyeMSwX6FcNHcP2x3CP3bqy7B70KjLzrpYhiooiYdWn1wQPUgx2gL4GtvVWOhS3xxltoB1ejiA1tYvCk3FTXBSvLkl770bgk0OTeH1fV8y/KzCZeb3s4ushE4Gb72SNo3gXdu67ib25rMIQj69wsRWK9F3dzdny+8paGAmN/bPiXhrHdPGkr8QOn/2w7pEA9ab9BPY2tTuh8U3EbdCd7ti+GG6U6h0yc5qiUuzaFLifJzROueyz7Ny4j5BZZNUTpc0EU3UZLl/SLEg5RnLASB8uOxl/t92WXsnlHZe/wjqYrlAS1dMRohmYmh7Cm15NWvhhikyXX6mUvEFSPBJ0F2gIHSeGZeAw1Tvz4HYqfCPBLIshmSMSrNtCcd0T92cnnRlNzGMUXklI+OjyYAHeeMgMjmQ1W04hvP07eyeqRCTQyrUhjBO8YLyJzxff6hAR4w93oJfsvMXBdSDFhbLCik1YunIvWw6YW+dgdN+MwB/zOXLj8X1BzUL+xusLgtMrBQVtt6PBMfJ5VlFR9djlcXq/t31mW0IFfdwkjBfye2O11+Xf2OoIEWE8yodhgD5boVyA+LVPSfqmumeS+1GNPEcY7zPWmMNA176+UFtDPgta1zTZ3YPfiPTGqYjRJOuk=
  - secure: aRYFodoRW0yXGnpQrg3XjHkRyIjShlvQfpnwjy8rwjK1SJS3EI7Z0gu2X56C8LqMvyYNeycZdzernmu5E73VT/ITvU+iWiUxtH1zJxfewf9FnupZJ53FRu+JhJl1i/fh8zq1MIVdXCpnIybtY/wqOhk8Lsz5FDfHU7WwG1bFPHqwzGVA/vPkX+41ClNrPYD7Sj1YFQUuqw0EE4/ZMasBIvdiCy4K60ME1YMd8NVtG/X/cftfOVhGhDVcG530miWQh6sGSP2fEm5YjmKlJZDREIThf8/IneRcKdOqj6oeO0J71To/1DD2XFMZwZMboY3XfI/ElRe5UM4/WZPMlsNrwTQiFIHhanroaQ+zeY9QQ6pqP61+SHcvjYmBK9Xb/G0UEAIJr0o2kLsDzUbrNylFJMK5ofwLgKhhTt952Z23uKfCrqTtFY1G0IuubqXvmeEmG5QUgO7ahuO0KKZsu1+uXYe8CzXnIQSUd8/zUaMe0Sw+pNwqddZ1A7SCu7rDt2EL1v46zaCswQjjV+E2kTk4L/umkVDs9MYtUry+iWg6yodBknSwtI7hwrXkkMtgjC8mo3HG7udOcvrCsPijUHZP71yTuexERsI+I6gTBj4HK0HlrlrSNJynFOZ5xR0OBeH7274ao7PDXWJwdYLQ3cXp273WhJlq0hQ/GwQWPp2YUGA=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
