CREATE TABLE wcf1_unkso_regulation (
	regulationID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description MEDIUMTEXT NOT NULL,
	identifier VARCHAR(20) NOT NULL,
	isHidden TINYINT(1) NOT NULL
);